### ISSUE TITLE
Instant pot Chicken fried rice does not appear?

### ISSUE THREAD

**Issue by reedkay** [chrisdaaz/forking#44]
I do not see my recipe on 
[https://chrisdaaz.github.io/forking/]

**Comment by reedkay** [comment]
Ok. I see that it was not included due to formatting. I attempted to change that.

**Comment by chrisdaaz** [comment]
fixed it with https://github.com/chrisdaaz/forking/commit/caee255fa3e2d3c35139542a214bb5ce2912617a

https://chrisdaaz.github.io/forking/recipes/instant-pot-chicken-fried-rice.html
