### ISSUE TITLE
My recipe doesn't appear in the cookbook

### ISSUE THREAD

**Issue by lstethers** [chrisdaaz/forking#46]
Hi Chris,
My recipe (Vegan Breakfast Cookies) isn't appearing in the class cookbook at https://chrisdaaz.github.io/forking/.  It looks like it was merged into your forking repo 6 days ago, so I'm wondering if I did something wrong that is making it not appear in the final product.

Thanks,
Lori

**Comment by chrisdaaz** [comment]
thanks for letting me know! there was a problem with the YAML frontmatter for the recipe (not your fault), so i fixed it with this commit: https://github.com/chrisdaaz/forking/commit/488cbb36a2579ea5b6c7e2612c022805d516d27d

Enjoy! https://chrisdaaz.github.io/forking/recipes/vegan-breakfast-cookies.html
